test_buffer: test_buffer.c ../include/*.h ../src/*.c
	gcc -m32 -std=c17 -Wall -I../include -ggdb -o test_buffer test_buffer.c -lm
test_lexer: test_lexer.c ../include/*.h ../src/*.c
	gcc -m32 -std=c17 -Wall -I../include -ggdb -o test_lexer test_lexer.c -lm
test_string: test_string.c ../include/*.h ../src/*.c
	gcc -m32 -std=c17 -Wall -I../include -ggdb -o test_string test_string.c -lm
test_symbol_table: test_symbol_table.c ../include/*.h ../src/*.c
	gcc -m32 -std=c17 -Wall -I../include -ggdb -o test_symbol_table test_symbol_table.c -lm
test_value: test_value.c ../include/*.h ../src/*.c
	gcc -m32 -std=c17 -Wall -I../include -ggdb -o test_value test_value.c -lm